apiVersion: v1
kind: Service
metadata:
  name: clean-base-service
spec:
  selector:
    app: clean-base
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP