---
proj:
  profile: ${proj_profile:dev}
spring:
  profiles:
    active: ${proj.profile}
---
spring:
  datasource:
    username: ${spring_datasource_username:sa}
    password: ${spring_datasource_password:p@ssw0rd}
    url: ${spring_datasource_url:jdbc:h2:mem:test}
    driver-class-name: ${spring_datasource_driver_class_name:org.h2.Driver}
  jpa:
    database: ${spring_jpa_database:h2}
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

---
logging:
  config: classpath:log/logback.xml

---
spring:
  application:
    name: clean-base

server:
  port: 8081

---
spring:
  messages:
    basename: i18n/messages/response_code,i18n/messages/message

---
# OpenApi & Swagger
springdoc:
  api-docs:
    enabled: true
  default-produces-media-type: application/json
  swagger-ui:
    enabled: true
    default-models-expand-depth: -1
---
---
# Tracing & Metrics & Probe
management:
  observations:
    annotations:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  otlp:
    tracing:
      endpoint: ${management_otlp_tracing_endpoint:https://otel-http-tempo-tracing.apps.cluster-nqq6f.dynamic.redhatworkshops.io/v1/traces}
  tracing:
    sampling:
      probability: ${management_tracing_sampling_probability:1.0}
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
      base-path: /actuator
      path-mapping:
        health: health
---
---
test:
  region: ${test_region:part-a}
server:
  servlet:
    context-path: ${server_servlet_context_path:/clean-base}

