---
spring:
  config:
    import:
      - classpath:jpa/application-jpa-dev.yml
      - classpath:swagger/application-swagger-dev.yml
---
test:
  region: ${test_region:part-a}
server:
  servlet:
    context-path: ${server_servlet_context_path:/clean-base}