spring:
  application:
    name: clean-base-services-consumer
  config:
    import: classpath:application-common.yml

  cloud:
    openfeign:
      client:
        additional-feign-base-packages: com.redhat,com.cub
        datasource:
          is-inherited: true
server:
  port: 8082



