---
spring:
  config:
    import: classpath:application-common.yml

---
spring:
  application:
    name: clean-base

server:
  port: 8081

---
generic:
  exception:
    extra-packages: 'com.redhat.cleanbase.account'

