---
spring:
  cloud:
    gateway:
      routes:
        # bff
        - id: bff-tax-fee
          uri: http://localhost:8082
          predicates:
            - Path=/bff/tax-fee/**
          filters:
            - ApiSwitch
            - DeviceId
            - SaveSession
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

