---
proj:
  profile: ${proj_profile:dev}
spring:
  profiles:
    active: ${proj.profile}
  config:
    import:
      - classpath:i18n/application-i18n.yml
      - classpath:log/application-log.yml
      - classpath:jpa/application-jpa.yml
      - classpath:swagger/application-swagger.yml
      - classpath:actuator/application-actuator.yml
