---
server:
  port: 8088

spring:
  application:
    name: cube-api-internal-gateway
  reactor:
    context-propagation: auto
---
# Tracing & Metrics & Probe
management:
  observations:
    annotations:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  otlp:
    tracing:
      endpoint: ${management_otlp_tracing_endpoint:https://otel-http-tempo-tracing.apps.cluster-nqq6f.dynamic.redhatworkshops.io/v1/traces}
  tracing:
    sampling:
      probability: ${management_tracing_sampling_probability:1.0}
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
---
logging:
  config: classpath:log/logback.xml
---
spring:
  cloud:
    gateway:
      routes:
          # bff
        - id: bff-tax-fee
          uri: http://bff-tax-fee:8080
          predicates:
            - Path=/bff/tax-fee/<channel>/<apiVersion>

          # biz
        - id: biz-tax-fee
          uri: http://biz-tax-fee:8080
          predicates:
            - Path=/biz/tax-fee/**

        - id: biz-card
          uri: http://biz-card:8080
          predicates:
            - Path=/biz/card/**

        - id: biz-audit-log
          uri: http://biz-audit-log:8080
          predicates:
            - Path=/biz/audit-log/**

        - id: biz-notification
          uri: http://biz-notification:8080
          predicates:
            - Path=/biz/notification/**

        - id: biz-nps
          uri: http://biz-nps:8080
          predicates:
            - Path=/biz/nps/**

        - id: biz-twd-account
          uri: http://biz-twd-account:8080
          predicates:
            - Path=/biz/twd-account/**

        - id: biz-user
          uri: http://biz-user:8080
          predicates:
            - Path=/biz/user/**

        - id: biz-security-verification
          uri: http://biz-security-verification:8080
          predicates:
            - Path=/biz/security-verification/**

      default-filters:
        - StripPrefix=2

