---
server:
  port: 8080

spring:
  application:
    name: cube-api-internal-gateway
---
spring:
  reactor:
    context-propagation: auto

  cloud:
    gateway:
      routes:
        - id: fee-tax
          uri: http://localhost:8081
          predicates:
            - Path=/fee-tax/**

---
# Tracing & Metrics & Probe
management:
  observations:
    annotations:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  otlp:
    tracing:
      endpoint: ${management_otlp_tracing_endpoint:https://otel-http-tempo-tracing.apps.cluster-nqq6f.dynamic.redhatworkshops.io/v1/traces}
  tracing:
    sampling:
      probability: ${management_tracing_sampling_probability:1.0}
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
---
logging:
  config: classpath:log/logback.xml
---
spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
